name: awesome_jaspr_components
description: An open-source Dart package that brings a Flutter-like development experience to the Jaspr framework.  With a familiar API and a rich set of components, you can easily build reactive web apps using Jaspr, just like you would in Flutter
version: 1.0.1
repository: https://github.com/jamiejayoss/awesome_jaspr_components

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  jaspr: ^0.16.0
  jaspr_router: ^0.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
