name: awesome_jaspr_components
description: Get the flutter development experience on a jaspr website.
version: 1.0.0
repository: https://github.com/jamiejayoss/awesome_jaspr_components

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  jaspr: ^0.16.0
  jaspr_router: ^0.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
